### ISSUE TITLE
MySQL 5.5 database seeding

### ISSUE THREAD

**Issue by hlogeon** [moharrum/laravel-geoip-world-cities#1]
Hi! I'm trying to use the package on with the defult mysql 5.5 installation

Here is a stack trace. I just want to add the ticket here to be able to add a comment if I resolve, so somebody else can find the solution.

[2016-03-22 20:39:50] local.ERROR: exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1148 The used command is not allowed with this MySQL version' in /home/oem/repos/venvast/backend/database/seeds/CitiesTableSeeder.php:46
Stack trace:
#0 /home/oem/repos/venvast/backend/database/seeds/CitiesTableSeeder.php(46): PDO->exec('LOAD DATA LOCAL...')
#1 /home/oem/repos/venvast/backend/vendor/laravel/framework/src/Illuminate/Database/Seeder.php(42): CitiesTableSeeder->run()
#2 /home/oem/repos/venvast/backend/database/seeds/DatabaseSeeder.php(18): Illuminate\Database\Seeder->call('CitiesTableSeed...')
#3 /home/oem/repos/venvast/backend/vendor/laravel/framework/src/Illuminate/Database/Console/Seeds/SeedCommand.php(61): DatabaseSeeder->run()
#4 [internal function]: Illuminate\Database\Console\Seeds\SeedCommand->fire()
#5 /home/oem/repos/venvast/backend/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)

**Comment by moharrum** [comment]
Hello hlogeon,

This is a PHP [bug](https://bugs.php.net/bug.php?id=62889), please install `php5-mysqlnd` instead of `php5-mysql` , if this does not work, try the workaround mentioned in the bug link.

Thanks.

**Comment by moharrum** [comment]
Since this is a known bug and you did not give a feedback in more than two months I'm closing this issue.
