### ISSUE TITLE
Syntax error unexpected '::' after 'php artisan vendor:publish'

### ISSUE THREAD

**Issue by pimduijst** [moharrum/laravel-geoip-world-cities#4]
Executed all the instructions as written I get the following error after I execute `php artisan vendor:publish` on the commandline:

```
 [Symfony\Component\Debug\Exception\FatalErrorException]  
  syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM)
```

I also found this error in the errorlog:

`/vendor/moharrum/laravel-geoip-world-cities/src/LaravelGeoIPWorldCitiesServiceProvider.php on line 72`

showing this line of code:

`if(((double) $this->app::VERSION) === 5.4) {`

I also noticed a similar like syntax on the lines 101 and 119.

I am running Laravel 5.4 and PHP 5.6.27

Can someone help me out with this?

**Comment by moharrum** [comment]
Hello @pimduijst ,

I'm running PHP 7 and all looks good.

Trying to reproduce with PHP 5...

**Comment by pixxet** [comment]
@pimduijst 

in the file 
LaravelGeoIPWorldCitiesServiceProvider.php

just replace all lines with:
`if(((double) $this->app::VERSION) === 5.4) {`

with this:
`$thisApp = $this->app;
        if(((double) $thisApp::VERSION) === 5.4) {`

**Comment by moharrum** [comment]
Fixed, I will commit the new changes shortly.

Thanks everyone.

**Comment by moharrum** [comment]
Fixed now.

Thanks.
