### ISSUE TITLE
UTF-8 support

### ISSUE THREAD

**Issue by mfmsaadi** [moharrum/laravel-geoip-world-cities#5]
**Can you please save the text files as UTF-8 fromat ? ( I do it manullay every time I install the package )**

**Comment by pimduijst** [comment]
Hi @mfmsaadi did you manage to get the package working? As you see my issue, I haven't maybe you can help me out?

**Comment by moharrum** [comment]
Hi @mfmsaadi , 

Can you explain more, do you use a tool for conversion or just update file encoding using a text editor?

**Comment by mfmsaadi** [comment]
Hi @moharrum, 
Yes just update the file encoding using a rext editor :)

**Comment by mfmsaadi** [comment]
Hi @pimduijst, 
Sorry that I didn't see your comment before !
I think @pixxet helped you in your issue thread :)

**Comment by moharrum** [comment]
Yup, thanks @pimduijst for the quick fix.

This is now fixed in 2.3.1
