### ISSUE TITLE
Laravel 5.5 support

### ISSUE THREAD

**Issue by MCMatters** [moharrum/laravel-geoip-world-cities#6]
And here we go again.
https://github.com/moharrum/laravel-geoip-world-cities/blob/43c2a4f65de1a444d906f879c72510749f3580ce/src/LaravelGeoIPWorldCitiesServiceProvider.php#L74
In 5.5 this line is not working. Please, tell me, why didn't you accept my PR? Your package is for Laravel 5.x, if you look into 
https://github.com/laravel/framework/blob/262b813fc88810071f8282722a89eb5199cb398a/src/Illuminate/Container/Container.php#L268
you see that Laravel uses method `singleton` from 5.x version, so why do you do this check? Please use `singleton` method instead `share` and without redundant checks

**Comment by moharrum** [comment]
Hello @MCMatters

Sorry about that my friend, I was busy at that time and I forgot to fix this for good. Anyway, can you please re open your PR again so I can merge? 

Thanks again.

**Comment by MCMatters** [comment]
Yes, sure :)
https://github.com/moharrum/laravel-geoip-world-cities/pull/7

**Comment by moharrum** [comment]
Thanks again @MCMatters ,

Merged to master, will release a new version as soon as I get to my PC.

**Comment by MCMatters** [comment]
No problem 😉
